### ISSUE TITLE
Seg fault on start

### ISSUE THREAD

**Issue by brownnrl** [mckset/KD100#3]
Hi!  So thanks for writing this driver!  I was hoping to get it running on my Unbuntu 20.04.06 box.

```
LSB Version:	core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
```

However, it just segfaults.  I got the core dump and ran it through GDB and got the following.  I ran it both as my regular user and as sudo to the same resulting stack.

```
Core was generated by `KD100'.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Section `.reg-xstate/1702572' in core file too small.
#0  0x00005615c2645d22 in main (args=1, in=0x7ffc91196978) at KD100.c:429
429		libusb_set_option(*ctx, LIBUSB_OPTION_LOG_LEVEL, 0);
[Current thread is 1 (Thread 0x7f33689c9b80 (LWP 1702572))]
```

I'll keep poking at it and if I find any resolution I'll put it here, though I don't have much familiarity with the libusb library (but what a fun way to learn!)  :)

Thanks again.

**Comment by brownnrl** [comment]
So just commenting out line 429 and tested everything setting up a new `default.cfg` file and all is working!  I don't know what's causing that line to fail but the libusb logging isn't giving me any info I am using.  So commenting it out seems like a good workaround.

I can chase this down further if it's helpful with a little guidance, or you can close this ticket.  Since the code doesn't work as is (at least for my system), I'll leave this ticket open in case anyone else has the same issue.  But it works great.  I like it better than the windows version of the driver because there is this awful delay between the swap functions.

**Comment by mckset** [comment]
Strange that it would run after commenting out that line. I will investigate what's causing it. I've also been meaning to rewrite the way it reads the config file but by the sounds of it, that's not what is causing the problem.

**Comment by brownnrl** [comment]
Copy that, if there's anything you'd like me to try (printing something out from libusb or etc) let me know.

**Comment by mckset** [comment]
By the looks of it, it seems that the segmentation fault is bug in the version of libusb that ships with Ubuntu 20.04. I was able to reproduce the problem right away and commenting out line 429 did resolve the issue. Luckily, that line was only there for setting the debug level for libusb to use so the driver should still work without it. Interestingly, setting the environment variable LIBUSB_DEBUG to a number also will crash the driver since that will force libusb to try to set a debug level. I will comment out that line for future releases.

**Comment by mckset** [comment]
After further testing I have found out that the segmentation fault is not a bug. For some reason, the way I was passing the "ctx" variable to the set_option function caused segmentation faults only on certain distros. I will push an update with the fix tomorrow but the line will remain commented out since it's only for debugging.
